### ISSUE TITLE
Terraform wrapper

### ISSUE THREAD

**Issue by cvarjao** [DerekRoberts/bcoc#40]
As a developer
I want to use terraform scripts/modules
so that I can deploy my app

Acceptance criteria:
when running `npx @bcgov/nrdk tool:terraform -version`
I should see the version of terraform that is being installed/managed by nrdk. e.g.:
```
Terraform v0.14.5
```` 

Examples:
`tool:mvn` command -> https://github.com/BCDevOps/nrdk/blob/master/src/commands/tool/mvn.ts
Maven Provider implementation: https://github.com/BCDevOps/nrdk/blob/master/src/tools/maven.ts

**Comment by DerekRoberts** [comment]
Demoed in nrdk fork https://github.com/DerekRoberts/nrdk/pull/1

**Comment by DerekRoberts** [comment]
Addressed in bcdevops/nrdk.
